# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_battle_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
