# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_battle_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='count',
        ),
    ]
